import React, { useState, useEffect, useRef, useMemo, memo } from 'react';
import { Menu, X, ArrowRight, ArrowLeft, Globe, Shield, Zap, TrendingUp, FileText, Anchor, Linkedin, ExternalLink, Users, Coins, Briefcase, ScanLine, BarChart3, Download, AlertCircle, Check, Leaf, Info, Scale, BookOpen, ChevronDown, ChevronUp, Tag, ShieldCheck, Wind, Gavel, MicOff, Lock, HelpCircle, Eye, AlertTriangle, CheckCircle, Mail, Copy, RefreshCw, ShieldAlert, Search, UserX, Flag } from 'lucide-react';

/* ==================================================================================
   1. DESIGN SYSTEM & TOKENS
   ================================================================================== */

const THEME = {
  colors: {
    background: "#E0E5EC",
    surface: "#E0E5EC",
    text: {
      primary: "#313b4e",
      secondary: "#64748b",
      light: "#94a3b8",
      inverse: "#FFFFFF"
    },
    accent: {
      primary: "#0d9488",
      secondary: "#14b8a6",
      light: "#f0fdfa",
    },
    risk: {
      critical: "#EF4444",
      high: "#F97316",
      medium: "#EAB308",
      low: "#22C55E"
    }
  },
  shadows: {
    neumorphic: "9px 9px 16px rgb(163,177,198,0.6), -9px -9px 16px rgba(255,255,255,0.5)",
    neumorphicInset: "inset 9px 9px 16px rgb(163,177,198,0.6), inset -9px -9px 16px rgba(255,255,255,0.5)",
    floating: "20px 20px 60px #bebebe, -20px -20px 60px #ffffff"
  }
};

/* ==================================================================================
   2. DATA LAYER (CMS)
   ================================================================================== */

const SITE_CONTENT = {
  brand: {
    name: "HOOOP",
    est: "Est. 2025",
    logoImage: "/THE-HOOO-COLLECTIVEP_without-shadow.png",
    contactEmail: "hello@hooop.in",
  },
  hero: {
    titleLine1: "Growth",
    titleLine2: "Re-Imagined",
    subtitle: "We align customer behaviour with sustainable choices, designing for impact and business growth.",
    buttonText: "Our Offerings",
    collectiveButtonText: "Meet the Collective",
    linkText: "Read our manifesto"
  },
  thinking: {
    title: "Our Thinking",
    subtitle: "Essays on the intersection of climate, capital, and culture.",
    featuredTool: {
        title: "Sense by HOOOP",
        desc: "Use our logic powered brand narrative tool to stress-test your claims against greenwashing risks.",
        cta: "Run Analysis"
    },
    posts: [
      { 
          slug: "alpha-in-authenticity",
          title: "The Alpha in Authenticity: Why Greenwashing Kills Valuation", 
          category: "Climate Finance", 
          date: "October 12, 2025", 
          desc: "Investors are no longer just looking at returns; they are looking at risk. Misleading environmental claims are becoming a primary liability in climate funding rounds.",
          content: [
            "In the high-stakes world of climate finance, the definition of 'alpha'—the excess return on an investment—is shifting. For decades, alpha was generated by information asymmetry or operational efficiency. Today, in the context of ESG (Environmental, Social, and Governance) investing, alpha is increasingly found in authenticity. Conversely, greenwashing has mutated from a PR nuisance into a tangible valuation killer.",
            "Recent regulatory crackdowns by bodies like the SEBI in India and the CMA in the UK have fundamentally altered the risk profile of sustainable investments. When a company exaggerates its environmental credentials, it isn't just misleading a consumer; it is mispricing an asset. Investors are waking up to the reality that a 'green premium' based on shaky claims is actually a 'green bubble' waiting to burst.",
            "Consider the due diligence process for Series A and B rounds in 2025. Funds are no longer satisfied with slide decks promising 'net-zero aspirations'. They are deploying forensic carbon accountants to audit supply chains. They are using satellite imagery to verify reforestation claims. In this environment, a brand narrative that outpaces actual impact is a liability. It suggests a management team that prioritizes optics over operations—a red flag for any serious investor.",
            "The financial implications of greenwashing allegations are severe. Beyond the immediate legal fines—which, under new guidelines like India’s CCPA, are becoming substantial—there is the cost of the 'trust discount'. Once a brand is flagged for deceptive practices, the market applies a permanent discount to its future claims. Customer acquisition costs (CAC) spike as skepticism rises. Employee retention drops as purpose-driven talent exits. The brand equity, painstakingly built over years, evaporates overnight.",
            "For founders and CMOs, the lesson is clear: Authenticity is a competitive moat. Building a brand on verifiable, data-backed impact might be slower than spinning a green fairytale, but it builds a valuation that holds up under scrutiny. In the new economy, the most valuable asset on your balance sheet isn't just your IP; it's your integrity."
          ]
      },
      { 
          slug: "brand-strategy-cynical",
          title: "Brand Strategy in the Age of the Cynical Consumer", 
          category: "Brand Strategy", 
          date: "September 28, 2025", 
          desc: "How to build a narrative that survives the scrutiny of Gen Z. It's not about being perfect; it's about being transparent about your imperfections.",
          content: [
            "We have entered the age of the 'Cynical Consumer'. This isn't cynicism born of apathy, but of exhaustion. Gen Z and Millennial consumers have been bombarded with 'eco-friendly', 'natural', and 'sustainable' claims for the better part of a decade. They have seen oil giants claim to be green champions and fast fashion behemoths launch 'conscious' collections while doubling production. The result? A default setting of disbelief.",
            "For a brand strategist, this presents a terrifying challenge. How do you communicate impact when your audience assumes you are lying? The traditional marketing playbook—highlight the good, hide the bad, and polish the narrative—is dead. In 2025, perfection is suspicious. Vulnerability is the new currency of trust.",
            "The brands winning in this era are those practicing 'Radical Transparency'. They don't just publish a sustainability report; they publish their failures. They admit that their packaging is only 80% recyclable because the technology for the last 20% doesn't exist yet at scale. They openly discuss the carbon cost of their logistics and invite consumers to help solve it. This approach disarms the cynical consumer because it validates their skepticism.",
            "It shifts the dynamic from a brand preaching from a pedestal to a brand partnering with its community on a difficult journey. It transforms the brand promise from 'We are saving the world' to 'We are trying to do better, and here is the proof'.",
            "To build a narrative that survives scrutiny, marketers must move from 'storytelling' to 'truth-telling'. Every claim must be backed by accessible data (QR codes to supply chain maps, for instance). Adjectives must be replaced by nouns and numbers. 'Better for the planet' is a lie; '40% less water usage than industry average' is a fact. In the age of the cynical consumer, facts are the only story that sells."
          ]
      }
    ]
  },
  prvaah: {
    title: "prvaah",
    sanskritMeaning: "flow in Sanskrit",
    description1: (
      <span>
        Created by <a href="https://www.everloop.agency/" target="_blank" rel="noreferrer" className="text-teal-600 hover:underline font-bold">Everloop.Agency</a> and <a href="https://www.hooop.in" target="_blank" rel="noreferrer" className="text-teal-600 hover:underline font-bold">HOOOP Collective</a>, Prvaah guides enterprises across India, EU, and the UK in ESG compliance and responsible expansion.
      </span>
    ),
    pillars: [
      { icon: "shield", label: "Compliance", desc: "Enter with credibility: ESG disclosure mapping, anti-greenwashing assessment." },
      { icon: "zap", label: "Capability", desc: "Equip your team: Sustainability training, leadership workshops & industry playbooks." },
      { icon: "globe", label: "Access", desc: "Navigate new markets: Market intelligence, cultural insights & investor introductions." },
      { icon: "file", label: "Pilots", desc: "Test & adapt: Go-to-market pilots, product validation & circular supply-chains." },
      { icon: "trending", label: "Scale", desc: "Expand responsibly: Long-term ESG integration, green media & impact measurement." },
      { 
        icon: "recycle",
        label: "Circularity Impact measurement & articulation",
        desc: "You want to communicate to the industry and customers the circularity or broader environmental benefits your product or business delivers? We can help you measure your impact, optimise your circularity outcomes and communicate it in a way that speaks to your target audience and keeps you clear of greenwashing accusations."
      }
    ],
    testimonials: [
      {
        text: "At Everloop, we see Pravah as a continuum — not just an entry point but a journey. From ESG alignment to market pilots and long-term resilience, this platform helps sustainable enterprises flow between the UK and India with confidence, purpose, and accountability.",
        name: "Marina Bradford",
        role: "Director, Everloop.Agency",
        image: "/Marina Bradford.jpg"
      },
      {
        text: "The India–UK agreement creates a genuine opportunity for sustainable enterprises to expand into new markets. It also strengthens digital trade, supports sustainability goals, and empowers MSMEs and inclusive enterprises to expand globally.",
        name: "Arvind Nair",
        role: "Founding Partner, HOOOP",
        image: "/Arvind.jpg"
      }
    ]
  },
  offerings: [
    { title: "Strategy & Creative", desc: "Refining marketing strategy by embedding sustainability into the core of brand transformation." },
    { title: "Journey Interventions", desc: "Embedding sustainability-driven nudges into customer, partner, and employee journeys." },
    { title: "Media & Intelligence", desc: "Tools enabling audience tracking to benchmark against ESG metrics and reduce carbon footprint." },
    { title: "Digital Sustainability", desc: "Optimising digital experiences for minimal environmental impact while maximising influence." }
  ],
  collective: [
    {
      name: "Arvind Nair",
      role: "Growth & Sustainability",
      desc: "Helping build marketing as a force for sustainable business to help narrow the value action gap. Formerly Global VP at Mirum India.",
      img: "/Arvind.jpg",
      linkedin: "https://www.linkedin.com/in/arvindbnair/"
    },
    {
      name: "Radhika Sharda",
      role: "Stakeholder Engagemnt, PR and Communications",
      desc: "With 15+ years of experience in brand and communications, Radhika specializes in translating sustainability visions into execution-ready frameworks, driving organizational excellence and scalable growth.",
      img: "/radhika.jpg",
      linkedin: "https://www.linkedin.com/in/radhika-sharda-83129b19/"
    },
    {
      name: "Maya D'Souza",
      role: "Circular Economy Policy",
      desc: "Expert on circular economy policy and practice. Focused on systems design and policy frameworks for sustainable impact.",
      img: "/MayaF.png",
      linkedin: "https://www.linkedin.com/in/maya-de-souza-12b16aa/"
    },
    {
      name: "Paromita Mukhopadhyay",
      role: "Environmental Law & Policy",
      desc: "Leads environmental law and policy thinking at HOOOP with 20+ years of experience. Consultant for funds monitoring regulatory and policy developments.",
      img: "/Paromita.jpg",
      linkedin: "https://www.linkedin.com/in/paromita-mukhopadhyay-nair-bb24447/"
    },
    {
      name: "Shujoy Dutta",
      role: "Brand Strategy",
      desc: "Blending brand with sustainability to craft impactful brand strategies.",
      img: "/shujoy.jpg",
      linkedin: "https://www.linkedin.com/in/shujoy-dutta-05599219/"
    },
    {
      name: "Rachana Lokhande",
      role: "Sustainable Media Strategy",
      desc: "25+ years leadership in media & tech. Former Co-CEO of Kinetic Worldwide. Advancing the concept of sustainable media to drive climate-positive impact.",
      img: "/Rachna.jpg",
      linkedin: "https://www.linkedin.com/in/rachanadlokhande/"
    }
  ],
  research: {
    title: "Research & Reports",
    subtitle: "Intelligence for the modern sustainable marketing agency.",
    intro: "Our reports combine rigorous data analysis with actionable insights on Circular Economy India, Sustainable Media, and Greenwashing in Marketing.",
    reports: [
        { title: "The State of Greenwashing in Marketing: India 2025", category: "Compliance", desc: "A comprehensive audit of 500+ Indian D2C brands. We analyze how greenwashing in marketing is evolving under new CCPA guidelines and what it means for your brand." },
        { title: "Sustainable Marketing in India: The Consumer Paradox", category: "Consumer Behavior", desc: "Decoding the value-action gap. Why 78% of Indians want sustainable products but only 12% buy. A guide for sustainability marketing professionals." },
        { title: "Circular Economy India: The Fashion Playbook", category: "Operations", desc: "Moving beyond recycling. Case studies on how shifting to a circular economy in India impacts the bottom line for mid-sized apparel brands." },
        { title: "Sustainable Media: Decarbonizing Digital Ads", category: "Digital Impact", desc: "The unseen carbon footprint of your ad spend. Benchmarks and best practices for implementing a sustainable media strategy." },
        { title: "The Future of the Sustainable Marketing Agency", category: "Industry Trends", desc: "How agencies are evolving from 'selling green' to 'designing growth'. What CMOs need to look for in their next partner." }
    ]
  }
};

const SENSE_TERMS = [
    { word: "eco-friendly", risk: "High", category: "Vague Claim", reference: "CCPA Clause 5(a)", tip: "Vague. Banned under CCPA Clause 5(a) without specific proof. Use specific metrics like 'biodegradable in 28 days'." },
    { word: "eco friendly", risk: "High", category: "Vague Claim", reference: "CCPA Clause 5(a)", tip: "Vague. Banned under CCPA Clause 5(a) without specific proof. Use specific metrics." },
    { word: "good for the planet", risk: "Critical", category: "Hyperbole", reference: "CCPA Clause 5(a)", tip: "Hyperbole. Implies net positive impact which is rarely true." },
    { word: "green product", risk: "High", category: "Vague Claim", reference: "FTC Green Guides", tip: "Meaningless. 'Green' has no legal definition." },
    { word: "planet-safe", risk: "Critical", category: "Absolute Claim", reference: "CCPA Clause 6(5)", tip: "Absolute claim. Nothing is 100% safe for the planet." },
    { word: "sustainable choice", risk: "Medium", category: "Generic Claim", reference: "ASCI Guidelines", tip: "Generic. Verify against specific lifecycle data." },
    { word: "better for the earth", risk: "High", category: "Comparative Claim", reference: "CCPA Clause 6(4)", tip: "Better than what? Needs a clear baseline comparison." },
    { word: "clean alternative", risk: "Medium", category: "Undefined Term", tip: "Undefined term. 'Clean' how? Energy? Waste? Toxins?" },
    { word: "nature-approved", risk: "High", category: "Puffery", tip: "Marketing fluff. Nature doesn't approve products." },
    { word: "earth-positive", risk: "High", category: "Regenerative Claim", tip: "Requires proof of regenerative impact, not just 'less bad'." },
    { word: "made responsibly", risk: "Medium", category: "Undefined Term", tip: "Define 'responsibly'. Look for SA8000 or Fair Trade." },
    { word: "good for the earth", risk: "High", category: "Vague Claim", tip: "Vague and hyperbolic. Does it regenerate the earth or just damage it less?" }, 
    { word: "good for nature", risk: "High", category: "Vague Claim", tip: "Similar to 'Good for the Earth'. Too broad to be legally substantiated." }, 
];

/* ==================================================================================
   3. UTILITY COMPONENTS & HOOKS
   ================================================================================== */

const iconMap = {
  coins: Coins,
  briefcase: Briefcase,
  scan: ScanLine,
  shield: Shield,
  file: FileText,
  micoff: MicOff,
  check: CheckCircle,
  eye: Eye,
  alert: AlertTriangle,
  info: Info,
  zap: Zap,
  chart: BarChart3,
  x: X,
  users: Users,
  globe: Globe,
  trending: TrendingUp,
  leaf: Leaf,
  scale: Scale,
  tag: Tag,
  userx: UserX,
  flag: Flag
};

const getIconComponent = (name) => iconMap[name] || Users;

const ImageWithFallback = ({ src, alt, className }) => {
  const [imgSrc, setImgSrc] = useState(src);
  return <img src={imgSrc} alt={alt} className={className} onError={() => setImgSrc("https://placehold.co/400x400?text=Image+Not+Found")} />;
};

const SoftCard = ({ children, className = "", onClick, hoverEffect = true, id = "", role, ariaLabel }) => {
  const baseClasses = `bg-[${THEME.colors.surface}] rounded-[30px] shadow-[${THEME.shadows.neumorphic}] ${hoverEffect ? `hover:shadow-[${THEME.shadows.neumorphicInset}]` : ''} transition-all duration-300 ease-in-out ${className}`;
  
  if (onClick) {
    return (
      <button 
        id={id} 
        onClick={onClick} 
        className={`${baseClasses} text-left w-full cursor-pointer focus:outline-none focus:ring-2 focus:ring-teal-500`}
        aria-label={ariaLabel}
        type="button"
      >
        {children}
      </button>
    );
  }

  return (
    <div id={id} className={baseClasses} role={role} aria-label={ariaLabel}>
      {children}
    </div>
  );
};

const VerticalPill = ({ height = "h-64", className = "" }) => (
  <div className={`w-16 ${height} bg-[${THEME.colors.surface}] rounded-full shadow-[${THEME.shadows.neumorphic}] ${className}`} />
);

const ScrollReveal = ({ children, className = "", delay = 0 }) => {
    const [isVisible, setIsVisible] = useState(false);
    const domRef = useRef();
    useEffect(() => {
        const observer = new IntersectionObserver(entries => entries.forEach(entry => setIsVisible(entry.isIntersecting)));
        const currentRef = domRef.current;
        if (currentRef) observer.observe(currentRef);
        return () => { if (currentRef) observer.unobserve(currentRef); };
    }, []);
    return <div ref={domRef} style={{ transitionDelay: `${delay}ms` }} className={`transition-all duration-1000 ease-out transform ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'} ${className}`}>{children}</div>;
};

const ConcentricCircles = memo(() => (
  <div className="fixed inset-0 pointer-events-none z-0 overflow-hidden flex items-center justify-center" aria-hidden="true">
    <div className="absolute w-[800px] h-[800px] border border-white/40 rounded-full" />
    <div className="absolute w-[1200px] h-[1200px] border border-white/30 rounded-full" />
    <div className="absolute w-[1600px] h-[1600px] border border-white/20 rounded-full" />
  </div>
));

const HooopLogo = ({ className = "w-10 h-10" }) => (
  <ImageWithFallback src={SITE_CONTENT.brand.logoImage} alt="HOOOP Logo" className={`object-contain ${className}`} />
);

/* ==================================================================================
   4. FEATURE MODULES (VIEWS)
   ================================================================================== */

/* --- MODULE: BLOG --- */
const BlogPostView = memo(({ post, onBack }) => (
  <div className="min-h-screen pt-24 pb-20 px-6 animate-fade-in-up">
    <div className="max-w-3xl mx-auto bg-white rounded-[2.5rem] p-8 md:p-12 shadow-xl border border-gray-100 relative">
      <button 
        onClick={onBack}
        className="absolute top-8 right-8 p-3 rounded-full bg-gray-100 hover:bg-gray-200 text-gray-500 transition-colors z-10"
        aria-label="Close article"
      >
        <X size={20} />
      </button>

      <div className="mb-8">
        <div className="flex items-center gap-3 mb-4">
           <span className="px-3 py-1 bg-teal-50 text-teal-600 rounded-full text-xs font-bold uppercase tracking-widest">{post.category}</span>
           <span className="text-gray-400 text-xs font-mono">{post.date}</span>
        </div>
        <h1 className="text-3xl md:text-5xl font-black text-gray-900 mb-6 leading-tight">{post.title}</h1>
        <p className="text-xl text-gray-500 font-medium leading-relaxed border-l-4 border-teal-500 pl-4">{post.desc}</p>
      </div>

      <div className="prose prose-lg text-gray-600 leading-relaxed space-y-6">
         {post.content.map((paragraph, idx) => (
            <p key={idx}>{paragraph}</p>
         ))}
      </div>

      <div className="mt-12 pt-12 border-t border-gray-100 text-center">
         <p className="text-sm text-gray-400 font-bold uppercase tracking-widest mb-4">Share this perspective</p>
         <div className="flex justify-center gap-4">
            <button className="p-3 rounded-full bg-blue-50 text-blue-600 hover:bg-blue-100 transition-colors" aria-label="Share on LinkedIn"><Linkedin size={20} /></button>
            <button className="p-3 rounded-full bg-gray-50 text-gray-600 hover:bg-gray-100 transition-colors" aria-label="Copy link" onClick={() => navigator.clipboard.writeText(window.location.href)}><Copy size={20} /></button>
         </div>
      </div>
    </div>
  </div>
));

/* --- MODULE: SENSE TOOL --- */
const SenseAnalysisView = memo(() => {
    const [text, setText] = useState("");
    const [result, setResult] = useState(null);
    const [error, setError] = useState("");

    const escapeRegExp = (str) => str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const analyze = () => {
        const trimmed = text.trim();
        if (!trimmed) {
            setError("Please paste a claim or paragraph to analyze.");
            setResult(null);
            return;
        }
        setError("");
        const hitsMap = new Map();
        SENSE_TERMS.forEach((term) => {
            const pattern = new RegExp(`\\b${escapeRegExp(term.word)}\\b`, "i");
            if (pattern.test(trimmed) || (term.word.split(' ').length > 1 && trimmed.toLowerCase().includes(term.word))) {
                 if(!hitsMap.has(term.word)) hitsMap.set(term.word, term);
            }
        });
        setResult(Array.from(hitsMap.values()));
    };

    return (
        <div className="w-full max-w-4xl mx-auto animate-fade">
            <div className="mb-8 grid md:grid-cols-2 gap-8 items-center">
                <div className="text-left pl-2">
                    <h2 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6 leading-tight">
                        Does it make <br/><span className="text-gray-400">Sense?</span>
                    </h2>
                    <p className="text-gray-500 font-medium mb-4">
                        Protect your reputation. Stress-test your environmental claims before you publish.
                    </p>
                </div>
                <div className="bg-blue-50 border border-blue-100 rounded-2xl p-4 flex items-start gap-3">
                    <Info className="text-blue-500 shrink-0 mt-1" size={20} />
                    <div>
                        <p className="text-xs font-bold text-blue-700 uppercase tracking-wide mb-1">Heuristic Scan Only</p>
                        <p className="text-xs text-blue-600 leading-relaxed">
                            This tool scans for common keywords associated with greenwashing risks. It does not replace legal counsel or third-party lifecycle assessment (LCA).
                        </p>
                    </div>
                </div>
            </div>

            <div className="relative mb-8 group">
                <label htmlFor="sense-textarea" className="block text-xs font-bold text-gray-400 mb-2 pl-1 uppercase tracking-widest">
                    Paste your claim or paragraph
                </label>
                <textarea 
                    id="sense-textarea"
                    value={text}
                    onChange={(e) => setText(e.target.value)}
                    placeholder="e.g., 'Our eco friendly washing powder uses 100% natural ingredients...'"
                    className={`soft-input w-full h-48 p-6 text-base text-gray-700 outline-none resize-none transition-all focus:ring-2 focus:ring-gray-200 rounded-2xl ${error ? 'border-red-500' : ''}`}
                    aria-invalid={!!error}
                ></textarea>
                {error && <p className="mt-2 text-xs font-bold text-red-500 flex items-center gap-1"><AlertTriangle size={12}/> {error}</p>}
                
                <div className="absolute bottom-4 right-4">
                    <button type="button" onClick={analyze} className="soft-btn-primary px-6 py-2 rounded-xl flex items-center gap-2 font-bold text-sm shadow-lg hover:shadow-xl transition-all bg-black text-white">
                        Analyze <ArrowRight size={16} />
                    </button>
                </div>
            </div>

            {result && (
                <div className="animate-fade mb-20">
                    <div className="flex items-baseline justify-between px-2 mb-4">
                        <h3 className="text-xl font-bold text-gray-900">Analysis Results</h3>
                        <span className="text-xs font-bold text-gray-400 uppercase">{result.length} Issues Found</span>
                    </div>
                    {result.length === 0 ? (
                        <div className="soft-card p-6 flex items-center gap-5 bg-white border border-green-100 rounded-2xl">
                            <div className="w-10 h-10 rounded-full bg-green-100 text-green-600 flex items-center justify-center shrink-0"><Check size={20} /></div>
                            <div>
                                <h4 className="font-bold text-gray-900">No Keywords Detected</h4>
                                <p className="text-gray-500 text-sm">Ensure your claims are backed by data.</p>
                            </div>
                        </div>
                    ) : (
                        <div className="space-y-4">
                            {result.map((item, i) => (
                                <div key={i} className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm">
                                    <div className="flex items-center gap-2 mb-2">
                                        <AlertCircle className="text-red-500" size={16} />
                                        <span className="font-bold text-gray-900">"{item.word}"</span>
                                        <span className="text-[10px] uppercase bg-gray-100 px-2 py-0.5 rounded font-bold">{item.risk} Risk</span>
                                    </div>
                                    <p className="text-sm text-gray-600 pl-6 mb-2">{item.tip}</p>
                                    {item.reference && <p className="text-xs text-gray-400 pl-6 flex items-center gap-1"><BookOpen size={10} /> {item.reference}</p>}
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            )}
        </div>
    );
});

/* --- MODULE: GREENWASHING PLAYBOOK --- */
const GreenwashingView = memo(({ navigateTo }) => {
   const scrollToId = (id) => {
        const element = document.getElementById(id);
        if (element) element.scrollIntoView({ behavior: 'smooth' });
    };

   return (
     <div className="w-full">
            <section id="gw-home" className="min-h-screen flex flex-col justify-center px-6 md:px-20 py-20 relative overflow-hidden">
                <div className="absolute top-0 right-0 w-[60vw] h-[60vw] bg-gradient-to-bl from-green-300/30 to-transparent rounded-full blur-3xl -translate-y-1/2 translate-x-1/3 pointer-events-none"></div>
                <div className="max-w-6xl mx-auto w-full grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
                <div className="z-10 order-2 lg:order-1 pt-10 md:pt-0">
                    <ScrollReveal>
                        <h1 className="text-4xl sm:text-5xl lg:text-7xl xl:text-8xl font-black text-gray-900 leading-[0.9] tracking-tighter mb-8">
                        Green <br/> Is The <br/> <span className="text-transparent bg-clip-text bg-gradient-to-r from-green-600 to-green-400">New Lie.</span>
                        </h1>
                    </ScrollReveal>
                    <ScrollReveal delay={600}>
                        <div className="flex flex-col sm:flex-row gap-4">
                        <button onClick={() => scrollToId('gw-gap')} className="px-8 py-4 bg-black text-white rounded-full font-bold shadow-lg hover:-translate-y-1 transition-transform flex items-center gap-2">
                            Mind The Gap <ArrowRight size={18} />
                        </button>
                        </div>
                    </ScrollReveal>
                </div>
                </div>
            </section>
            
             <section id="gw-playbook" className="min-h-screen flex flex-col justify-center px-6 md:px-20 py-20 bg-black text-white rounded-t-[3rem] mt-10">
                <div className="max-w-5xl mx-auto w-full py-10 text-center">
                    <h2 className="text-4xl md:text-6xl font-bold mb-4">The Playbook</h2>
                    <p className="text-gray-400 mb-12">Executing with Excellence</p>
                    <div className="mt-12 p-8 md:p-16 bg-white/5 rounded-[3rem] backdrop-blur-md border border-white/10 relative overflow-hidden group">
                        <h4 className="text-3xl md:text-5xl font-black mb-6 relative z-10">"Honesty is the new green."</h4>
                        <button onClick={() => navigateTo('sense')} className="relative z-10 bg-green-500 hover:bg-green-400 text-black px-12 py-5 rounded-full font-bold text-lg transition-all transform hover:scale-105 shadow-[0_0_20px_rgba(74,222,128,0.4)]">
                            Start The Journey
                        </button>
                    </div>
                </div>
            </section>
        </div>
    );
});

/* ==================================================================================
   5. NAVIGATION COMPONENT (Restored Top Nav)
   ================================================================================== */

const Navbar = ({ navItems, activeSection, navigateTo, isMenuOpen, setIsMenuOpen }) => (
  <nav className="fixed w-full z-50 bg-[#e0e5ec]/90 backdrop-blur-md border-b border-white/20 shadow-sm transition-all duration-300">
    <div className="max-w-7xl mx-auto px-6 lg:px-8">
      <div className="flex justify-between h-20 items-center">
        {/* Logo */}
        <div 
          className="flex items-center space-x-3 cursor-pointer" 
          onClick={() => navigateTo('home')}
        >
          <div className="w-10 h-10 rounded-xl bg-emerald-600 flex items-center justify-center text-white shadow-lg shadow-emerald-600/20">
            <Leaf size={24} />
          </div>
          <span className="text-2xl font-bold text-slate-800 tracking-tight">HOOOP</span>
        </div>

        {/* Desktop Nav */}
        <div className="hidden md:flex items-center space-x-8">
          {navItems.filter(item => !item.hidden).map((item) => (
             <button 
                key={item.id}
                onClick={() => navigateTo(item.id)}
                className={`text-sm font-bold tracking-wide transition-all ${
                  activeSection === item.id 
                    ? 'text-emerald-600 scale-105' 
                    : 'text-slate-500 hover:text-slate-800'
                }`}
             >
               {item.label}
             </button>
          ))}
          <button className="bg-slate-800 text-white px-6 py-2.5 rounded-xl font-medium shadow-lg hover:bg-slate-700 transition-all hover:-translate-y-0.5 ml-4">
            Contact Us
          </button>
        </div>

        {/* Mobile Button */}
        <div className="md:hidden">
          <button onClick={() => setIsMenuOpen(!isMenuOpen)} className="p-2 text-slate-600">
            {isMenuOpen ? <X /> : <Menu />}
          </button>
        </div>
      </div>
    </div>

    {/* Mobile Menu */}
    {isMenuOpen && (
      <div className="md:hidden bg-[#e0e5ec] border-t border-slate-200 p-4 space-y-2 shadow-xl animate-fade-in-up">
        {navItems.filter(item => !item.hidden).map((item) => (
            <button 
                key={item.id}
                onClick={() => navigateTo(item.id)}
                className={`block w-full text-left px-4 py-3 rounded-xl font-medium ${
                    activeSection === item.id 
                    ? 'bg-emerald-50 text-emerald-700' 
                    : 'text-slate-600 hover:bg-slate-200'
                }`}
            >
                {item.label}
            </button>
        ))}
        <button className="block w-full px-4 py-3 rounded-xl bg-slate-800 text-white font-medium text-center mt-4 shadow-md">
            Contact Us
        </button>
      </div>
    )}
  </nav>
);

/* ==================================================================================
   6. MAIN APP CONTROLLER
   ================================================================================== */

const App = React.forwardRef((props, ref) => {
  const [activeSection, setActiveSection] = useState('home');
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [senseTab, setSenseTab] = useState('analyzer');
  const [selectedPost, setSelectedPost] = useState(null);

  // Routing Handler (Simulated Hash Router)
  useEffect(() => {
    const handleHashChange = () => {
      const hash = window.location.hash.substring(1); 
      if (hash) {
        setActiveSection(hash);
        setSelectedPost(null); 
      } else {
        setActiveSection('home');
      }
    };
    handleHashChange();
    window.addEventListener('hashchange', handleHashChange);
    return () => window.removeEventListener('hashchange', handleHashChange);
  }, []);

  const navItems = useMemo(() => [
    { id: 'home', label: 'Home' },
    { id: 'prvaah', label: 'Prvaah' },
    { id: 'offerings', label: 'What We Do' },
    { id: 'thinking', label: 'Our Thinking' },
    { id: 'collective', label: 'Collective' },
    { id: 'sense', label: 'Sense', hidden: true },
    { id: 'greenwashing', label: 'Greenwashing', hidden: true },
    { id: 'research', label: 'Research', hidden: true } 
  ], []);

  const navigateTo = (id) => {
    window.location.hash = id;
    setActiveSection(id);
    setIsMenuOpen(false);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const openBlogPost = (post) => {
      setSelectedPost(post);
      window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  return (
    <div className={`min-h-screen font-sans text-[${THEME.colors.text.primary}] bg-[${THEME.colors.background}] selection:bg-black selection:text-white overflow-x-hidden relative`}>
      <ConcentricCircles />

      <Navbar 
        navItems={navItems}
        activeSection={activeSection}
        navigateTo={navigateTo}
        isMenuOpen={isMenuOpen}
        setIsMenuOpen={setIsMenuOpen}
      />

      {/* --- MAIN CONTENT AREA --- */}
      <main className="w-full min-h-screen relative z-10 px-4 sm:px-6 lg:px-20 pt-28 pb-16 flex flex-col">
          
          {/* HOME VIEW */}
          {activeSection === 'home' && (
            <section className="relative flex flex-col lg:flex-row items-center justify-center min-h-[85vh] animate-fade-in-up">
              <div className="w-full lg:w-1/2 z-10 flex flex-col justify-center items-start space-y-10 pl-4 lg:pl-12">
                <div className="flex flex-col">
                    <span className="text-xs font-bold tracking-[0.3em] uppercase text-gray-400 mb-4">{SITE_CONTENT.brand.est}</span>
                    <h1 className="text-4xl sm:text-5xl lg:text-8xl font-black text-[#313b4e] leading-[0.9] tracking-tight">
                      {SITE_CONTENT.hero.titleLine1} <br/>
                      <span className="text-transparent bg-clip-text bg-gradient-to-br from-black to-gray-600">{SITE_CONTENT.hero.titleLine2}</span>
                    </h1>
                </div>
                <p className="text-lg lg:text-xl text-gray-500 max-w-md leading-relaxed font-medium">{SITE_CONTENT.hero.subtitle}</p>
                <div className="flex flex-wrap gap-4 sm:gap-6 items-center">
                  <SoftCard onClick={() => navigateTo('offerings')} className="px-6 py-4 sm:px-8 flex items-center gap-3 text-black font-bold group cursor-pointer hover:scale-[1.02]" ariaLabel="View offerings">
                    <span>{SITE_CONTENT.hero.buttonText}</span>
                    <ArrowRight size={18} className="group-hover:translate-x-1 transition-transform" />
                  </SoftCard>
                  <SoftCard onClick={() => navigateTo('collective')} className="px-6 py-4 sm:px-8 flex items-center gap-3 text-gray-600 font-bold group cursor-pointer hover:text-teal-600 hover:scale-[1.02]" ariaLabel="Meet the collective">
                    <span>{SITE_CONTENT.hero.collectiveButtonText}</span>
                    <Users size={18} className="group-hover:scale-110 transition-transform"/>
                  </SoftCard>
                </div>
              </div>
              <div className="w-full lg:w-1/2 h-[50vh] lg:h-auto flex items-center justify-center relative mt-12 lg:mt-0">
                 <div className="relative w-[300px] h-[300px] lg:w-[500px] lg:h-[500px]">
                     <div className="absolute inset-0 rounded-full border-[40px] border-[#E0E5EC] shadow-[20px_20px_60px_#bebebe,-20px_-20px_60px_#ffffff] flex items-center justify-center animate-float">
                        <div className="w-full h-full rounded-full shadow-[inset_10px_10px_20px_#bebebe,inset_-10px_-10px_20px_#ffffff] flex items-center justify-center p-12">
                             <HooopLogo className="w-full h-full object-contain opacity-90" />
                        </div>
                     </div>
                 </div>
              </div>
            </section>
          )}

          {/* THINKING & BLOG VIEW */}
          {activeSection === 'thinking' && (
            selectedPost ? (
                <BlogPostView post={selectedPost} onBack={() => setSelectedPost(null)} />
            ) : (
                <section className="relative min-h-screen py-12 animate-fade-in-up">
                    <div className="max-w-4xl mx-auto px-6">
                        <div className="mb-20 text-center md:text-left">
                            <h2 className="text-4xl sm:text-5xl lg:text-7xl font-black text-[#313b4e] mb-6 tracking-tighter">
                                {SITE_CONTENT.thinking.title}
                            </h2>
                            <p className="text-xl text-gray-500 max-w-2xl font-light leading-relaxed">
                                {SITE_CONTENT.thinking.subtitle}
                            </p>
                        </div>
                        {/* Tool Promo */}
                        <div className="mb-20">
                            <SoftCard onClick={() => navigateTo('sense')} className="bg-gray-900 !rounded-[2.5rem] p-8 md:p-12 text-white relative overflow-hidden group cursor-pointer" hoverEffect={false}>
                                <div className="absolute top-0 right-0 w-64 h-64 bg-gradient-to-br from-green-500 to-transparent opacity-20 rounded-full blur-3xl transform translate-x-1/3 -translate-y-1/3"></div>
                                <div className="relative z-10 flex flex-col md:flex-row gap-8 items-start md:items-center justify-between">
                                    <div>
                                        <div className="flex items-center gap-2 mb-4">
                                            <div className="w-2 h-2 bg-green-400 rounded-full animate-pulse"></div>
                                            <span className="text-xs font-bold tracking-widest uppercase text-green-400">Featured Intelligence</span>
                                        </div>
                                        <h3 className="text-3xl font-bold mb-3 text-white">{SITE_CONTENT.thinking.featuredTool.title}</h3>
                                        <p className="text-gray-400 max-w-md text-sm leading-relaxed mb-6">
                                            {SITE_CONTENT.thinking.featuredTool.desc}
                                        </p>
                                        <span className="inline-flex items-center gap-2 text-sm font-bold border-b border-green-500 pb-1 hover:text-green-400 transition-colors">
                                            {SITE_CONTENT.thinking.featuredTool.cta} <ArrowRight size={16} />
                                        </span>
                                    </div>
                                    <ScanLine size={48} className="text-green-400 opacity-50" />
                                </div>
                            </SoftCard>
                        </div>
                        {/* Blog List */}
                        <div className="space-y-16 border-t border-gray-200 pt-16">
                            {SITE_CONTENT.thinking.posts.map((post, index) => (
                                <article key={index} className="group cursor-pointer" onClick={() => openBlogPost(post)}>
                                    <div className="flex flex-col md:flex-row gap-2 md:items-baseline justify-between mb-2">
                                        <span className="text-xs font-bold tracking-widest uppercase text-teal-600">{post.category}</span>
                                        <span className="text-xs text-gray-400 font-mono">{post.date}</span>
                                    </div>
                                    <h3 className="text-2xl md:text-3xl font-bold text-gray-900 mb-3 group-hover:text-teal-600 transition-colors duration-300">
                                        {post.title}
                                    </h3>
                                    <p className="text-gray-500 leading-relaxed max-w-2xl text-lg">
                                        {post.desc}
                                    </p>
                                    <div className="mt-4 flex items-center gap-2 text-sm font-bold text-gray-400 group-hover:text-teal-600 transition-colors">
                                        Read Article <ArrowRight size={14} />
                                    </div>
                                </article>
                            ))}
                        </div>
                    </div>
                </section>
            )
          )}

          {/* SENSE VIEW */}
          {activeSection === 'sense' && (
            <section className="relative min-h-screen py-12 animate-fade-in-up">
                <div className="max-w-6xl mx-auto px-6 mb-12">
                     <div className="flex gap-4 overflow-x-auto no-scrollbar pb-2">
                        {[
                            { id: 'analyzer', label: 'Analyzer', icon: ScanLine },
                            { id: 'checklist', label: 'Visual Audit', icon: Check },
                            { id: 'learn', label: 'Learn', icon: BookOpen }
                        ].map(tab => (
                            <button
                                key={tab.id}
                                onClick={() => setSenseTab(tab.id)}
                                className={`flex items-center gap-2 px-6 py-3 rounded-full text-sm font-bold transition-all whitespace-nowrap ${
                                    senseTab === tab.id 
                                    ? 'bg-gray-900 text-white shadow-lg' 
                                    : 'bg-white text-gray-500 hover:bg-gray-100 border border-gray-200'
                                }`}
                            >
                                <tab.icon size={16} />
                                {tab.label}
                            </button>
                        ))}
                     </div>
                </div>
                {senseTab === 'analyzer' && <SenseAnalysisView />}
                {senseTab === 'checklist' && <div className="text-center p-20 text-gray-400">Visual Audit Component (Placeholder for Optimization)</div>}
                {senseTab === 'learn' && <div className="text-center p-20 text-gray-400">Resources Component (Placeholder for Optimization)</div>}
            </section>
          )}

          {/* PRVAAH VIEW */}
          {activeSection === 'prvaah' && (
            <section className="min-h-screen py-12 animate-fade-in-up">
                <div className="max-w-6xl mx-auto px-6">
                    <div className="text-center mb-20">
                         <div className="flex justify-center mb-6">
                            <ImageWithFallback src="/Prvaah Logo.png" alt="Prvaah Logo" className="h-24 w-auto object-contain" />
                         </div>
                         <h2 className="text-4xl sm:text-5xl lg:text-7xl font-black text-[#313b4e] mb-4 tracking-tighter">
                            {SITE_CONTENT.prvaah.title}
                         </h2>
                         <p className="text-lg text-gray-400 italic mb-6">"{SITE_CONTENT.prvaah.sanskritMeaning}"</p>
                         <p className="text-xl text-gray-500 max-w-2xl mx-auto leading-relaxed">
                            {SITE_CONTENT.prvaah.description1}
                         </p>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-24">
                        {SITE_CONTENT.prvaah.pillars.map((pillar, idx) => {
                             const Icon = getIconComponent(pillar.icon);
                             return (
                                <SoftCard key={idx} className="p-8 group hover:-translate-y-1 transition-transform">
                                    <div className="w-14 h-14 rounded-2xl bg-[#E0E5EC] shadow-[inset_5px_5px_10px_#bebebe,inset_-5px_-5px_10px_#ffffff] flex items-center justify-center mb-6 text-teal-600 group-hover:scale-110 transition-transform">
                                        <Icon size={28} />
                                    </div>
                                    <h3 className="text-xl font-bold text-gray-800 mb-3">{pillar.label}</h3>
                                    <p className="text-sm text-gray-500 leading-relaxed">{pillar.desc}</p>
                                </SoftCard>
                             );
                        })}
                    </div>
                </div>
            </section>
          )}

          {/* GREENWASHING VIEW */}
          {activeSection === 'greenwashing' && <GreenwashingView navigateTo={navigateTo} />}

          {/* OFFERINGS VIEW */}
          {activeSection === 'offerings' && (
            <section className="py-12 min-h-screen animate-fade-in-up">
              <div className="max-w-6xl mx-auto px-6 mb-32">
                  <div className="flex flex-col lg:flex-row justify-between items-end mb-20">
                     <div>
                         <h2 className="text-4xl lg:text-6xl font-black text-[#313b4e] mb-4">What We Do</h2>
                         <p className="text-gray-500">Soft interventions for hard problems.</p>
                     </div>
                     <VerticalPill height="h-2" className="w-32 !rotate-0 hidden lg:block" />
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-8 lg:gap-12">
                     {SITE_CONTENT.offerings.map((card, idx) => (
                       <SoftCard key={idx} className="p-10 flex flex-col justify-between h-80 group">
                          <div>
                            <div className="w-12 h-12 rounded-2xl bg-[#E0E5EC] shadow-[5px_5px_10px_#bebebe,-5px_-5px_10px_#ffffff] flex items-center justify-center mb-6 text-black font-bold text-xl group-hover:text-white group-hover:bg-black transition-colors duration-300">
                               {idx + 1}
                            </div>
                            <h3 className="text-2xl font-bold text-[#313b4e] mb-4">{card.title}</h3>
                            <p className="text-gray-500 text-sm leading-relaxed">{card.desc}</p>
                          </div>
                       </SoftCard>
                     ))}
                  </div>
              </div>
            </section>
          )}

          {/* COLLECTIVE VIEW */}
          {activeSection === 'collective' && (
             <section className="py-12 min-h-screen animate-fade-in-up">
                <div className="mb-20 px-6 max-w-6xl mx-auto">
                   <h2 className="text-4xl lg:text-6xl font-black text-[#313b4e] mb-6">The Collective</h2>
                   <p className="text-gray-500 max-w-xl text-lg">
                      We are thinkers, technologists, communicators, and designers working to accelerate change.
                   </p>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 px-6 max-w-6xl mx-auto">
                   {SITE_CONTENT.collective.map((member, idx) => (
                       <SoftCard key={idx} className="p-8 flex flex-col items-center text-center group">
                          <div className="w-32 h-32 rounded-full bg-[#E0E5EC] shadow-[inset_5px_5px_10px_#bebebe,inset_-5px_-5px_10px_#ffffff] p-2 flex-shrink-0 mb-6">
                             <ImageWithFallback src={member.img} alt={member.name} className="w-full h-full object-cover rounded-full grayscale group-hover:grayscale-0 transition-all duration-500"/>
                          </div>
                          <div>
                             <h3 className="text-xl font-bold text-[#313b4e]">{member.name}</h3>
                             <p className="text-gray-400 font-bold text-xs uppercase tracking-widest mb-4 mt-2 h-8">{member.role}</p>
                             <p className="text-gray-500 text-xs leading-relaxed mb-6 h-20 overflow-hidden">{member.desc}</p>
                             <div className="flex justify-center gap-4">
                                {member.linkedin && (
                                <a href={member.linkedin} target="_blank" rel="noopener noreferrer" className="relative z-20" aria-label={`LinkedIn profile of ${member.name}`}>
                                    <Linkedin size={18} className="text-gray-400 hover:text-black cursor-pointer transition-colors"/>
                                </a>
                                )}
                             </div>
                          </div>
                       </SoftCard>
                   ))}
                </div>
             </section>
          )}
          
          {/* RESEARCH VIEW */}
          {activeSection === 'research' && (
             <section className="py-12 min-h-screen animate-fade-in-up">
                <div className="max-w-6xl mx-auto px-6">
                    <div className="text-center mb-20">
                        <h2 className="text-4xl lg:text-6xl font-black text-[#313b4e] mb-4">{SITE_CONTENT.research.title}</h2>
                        <p className="text-lg text-gray-500 max-w-2xl mx-auto">{SITE_CONTENT.research.subtitle}</p>
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                        {SITE_CONTENT.research.reports.map((item, idx) => {
                            const Icon = getIconComponent('chart');
                            return (
                            <SoftCard key={idx} className="p-8 flex flex-col justify-between h-80 group hover:-translate-y-2" onClick={() => {}} ariaLabel={`Download report: ${item.title}`}>
                                <div>
                                    <div className="flex justify-between items-start mb-6">
                                        <div className="p-3 rounded-2xl bg-[#E0E5EC] shadow-[inset_3px_3px_6px_#bebebe,inset_-3px_-3px_6px_#ffffff]">
                                            <Icon size={24} className="text-gray-600" />
                                        </div>
                                        <span className="text-xs font-bold uppercase tracking-widest text-teal-600 bg-teal-50 px-3 py-1 rounded-full">{item.category}</span>
                                    </div>
                                    <h3 className="text-xl font-bold text-gray-800 mb-4">{item.title}</h3>
                                    <p className="text-sm text-gray-500 leading-relaxed">{item.desc}</p>
                                </div>
                                <div className="mt-6 pt-6 border-t border-gray-200/50 flex items-center justify-between text-gray-400 group-hover:text-teal-600 transition-colors">
                                    <span className="text-xs font-bold uppercase tracking-widest">Download</span>
                                    <Download size={18} />
                                </div>
                            </SoftCard>
                        )})}
                    </div>
                </div>
            </section>
          )}

        <footer className="w-full py-12 mt-auto border-t border-gray-200/40 text-center">
            <p className="text-gray-400 text-xs font-medium uppercase tracking-widest">
                We are always open for a good conversation, write to us at <a href="mailto:hello@hooop.in" className="text-teal-600 hover:text-teal-800 transition-colors lowercase font-bold ml-1">hello@hooop.in</a>
            </p>
        </footer>
      </main>

      <style>{`
        @keyframes float { 0%, 100% { transform: translateY(0); } 50% { transform: translateY(-20px); } }
        .animate-float { animation: float 6s ease-in-out infinite; }
        .animate-fade-in-up { animation: fadeInUp 0.8s ease-out forwards; opacity: 0; transform: translateY(20px); }
        @keyframes fadeInUp { to { opacity: 1; transform: translateY(0); } }
        .no-scrollbar::-webkit-scrollbar { display: none; }
        .no-scrollbar { -ms-overflow-style: none; scrollbar-width: none; }
        html { scroll-behavior: smooth; }
        .soft-input { background: #F5F5F7; box-shadow: inset 4px 4px 8px #d1d4d9, inset -4px -4px 8px #ffffff; }
      `}</style>
    </div>
  );
});

export default App;
